- name: Ensure home folders are created
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
  loop: "{{ dot_boot_folders }}"
- name: Root tasks
  import_tasks: root_tasks.yml
  become: true
- name: Include tasks
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  loop_control:
    label: "tasks"
  loop:
    - setup_homebrew.yml